version: "3"

services:
    node:
        build: .
        working_dir: /app
        volumes: 
            - ./app:/app
        stdin_open: true
        tty: true
        ports: 
            - 3983:3000
            - 9005:9005
        extra_hosts:
            - localhost:192.168.1.188