version: "3"

services:
    node:
        build: .
        working_dir: /app
        volumes: 
            - ./app:/app
        stdin_open: true
        tty: true
        ports: 
            - 3000:3000
            - 9005:9005